import { Platform, StyleSheet } from 'react-native';

const headingFont = Platform.select({
  ios: 'Avenir Next',
  android: 'serif',
  default: 'serif',
});

const bodyFont = Platform.select({
  ios: 'Avenir Next',
  android: 'sans-serif',
  default: 'sans-serif',
});

const colors = {
  bgLight: '#FBF9F6',
  cardBg: '#FFFFFF',
  primary: '#1D3E2F',
  primaryLight: '#E5EDE9',
  accent: '#D96236',
  accentLight: '#FBECE7',
  textDark: '#2C2825',
  textMuted: '#8E867D',
  border: '#EBE5DF',
};

const shadows = {
  soft: {
    shadowColor: '#1D3E2F',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 12,
    elevation: 2,
  },
  medium: {
    shadowColor: '#1D3E2F',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 4,
  },
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.bgLight,
  },
  screen: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 20,
    paddingBottom: 60,
    paddingTop: 10,
  },
  hero: {
    borderRadius: 24,
    padding: 24,
    marginBottom: 24,
    marginTop: 10,
    ...shadows.medium,
  },
  heroTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 24,
  },
  eyebrow: {
    fontFamily: headingFont,
    color: 'rgba(255,255,255,0.7)',
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 1,
    marginBottom: 6,
  },
  heroTitle: {
    fontFamily: headingFont,
    color: '#FFFFFF',
    fontSize: 28,
    fontWeight: '800',
    marginBottom: 8,
  },
  heroSubtitle: {
    color: 'rgba(255,255,255,0.85)',
    fontSize: 14,
    lineHeight: 20,
    maxWidth: '85%',
  },
  heroStatus: {
    alignItems: 'flex-end',
  },
  heroStatusLabel: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 12,
    marginBottom: 8,
  },
  metricsRow: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    justifyContent: 'space-between',
  },
  metricCard: {
    alignItems: 'center',
    flex: 1,
  },
  metricLabel: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 11,
    marginBottom: 4,
  },
  metricValue: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  heroFootnote: {
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.15)',
    paddingTop: 16,
  },
  heroFootnoteText: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 12,
    lineHeight: 18,
  },
  card: {
    backgroundColor: colors.cardBg,
    borderRadius: 24,
    padding: 20,
    marginBottom: 20,
    ...shadows.soft,
  },
  sectionHeader: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontFamily: headingFont,
    color: colors.primary,
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 6,
  },
  sectionSubtitle: {
    color: colors.textMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  inlineTitle: {
    fontFamily: headingFont,
    color: colors.textDark,
    fontSize: 16,
    fontWeight: '700',
    marginTop: 10,
    marginBottom: 12,
  },
  stack: {
    gap: 12,
  },
  inputGroup: {
    gap: 12,
    marginBottom: 16,
  },
  inputRow: {
    flexDirection: 'row',
    gap: 12,
  },
  input: {
    flex: 1,
    minWidth: 0,
    backgroundColor: colors.bgLight,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    paddingHorizontal: 16,
    height: 52,
    fontSize: 15,
    color: colors.textDark,
  },
  textarea: {
    height: 100,
    paddingTop: 16,
    textAlignVertical: 'top',
  },
  primaryButton: {
    minWidth: 84,
    backgroundColor: colors.accent,
    borderRadius: 16,
    height: 52,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  primaryButtonWide: {
    backgroundColor: colors.accent,
    borderRadius: 16,
    height: 52,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    marginBottom: 12,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  secondaryButton: {
    minWidth: 84,
    backgroundColor: colors.primary,
    borderRadius: 16,
    height: 52,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    flex: 1,
  },
  secondaryButtonWide: {
    backgroundColor: colors.primary,
    borderRadius: 16,
    height: 52,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  secondaryButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '600',
  },
  ghostButton: {
    height: 52,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
  },
  ghostButtonText: {
    color: colors.textDark,
    fontSize: 15,
    fontWeight: '600',
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  pillRow: {
    flexDirection: 'row',
    backgroundColor: 'rgba(0,0,0,0.2)',
    borderRadius: 20,
    padding: 4,
  },
  pillButton: {
    paddingVertical: 6,
    paddingHorizontal: 16,
    borderRadius: 16,
  },
  pillButtonActive: {
    backgroundColor: '#FFFFFF',
    ...shadows.soft,
  },
  pillText: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 13,
    fontWeight: '600',
  },
  pillTextActive: {
    color: colors.primary,
  },
  statusBanner: {
    padding: 16,
    borderRadius: 16,
    marginBottom: 20,
    borderWidth: 1,
  },
  statusBannerLive: {
    backgroundColor: colors.primaryLight,
    borderColor: 'rgba(29, 62, 47, 0.1)',
  },
  statusBannerError: {
    backgroundColor: '#FDECEE',
    borderColor: 'rgba(217, 74, 74, 0.1)',
  },
  statusBannerIdle: {
    backgroundColor: colors.bgLight,
    borderColor: colors.border,
  },
  statusTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textDark,
    marginBottom: 4,
  },
  statusBody: {
    fontSize: 13,
    color: colors.textMuted,
    lineHeight: 18,
  },
  metaRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
  },
  metaCard: {
    flex: 1,
    backgroundColor: colors.bgLight,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  metaLabel: {
    fontSize: 11,
    color: colors.textMuted,
    marginBottom: 6,
  },
  metaValue: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textDark,
  },
  helperText: {
    fontSize: 12,
    color: colors.textMuted,
    lineHeight: 18,
    marginTop: 12,
    textAlign: 'center',
  },
  calendar: {
    borderRadius: 16,
    marginBottom: 20,
  },
  summaryRow: {
    flexDirection: 'row',
    gap: 12,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 20,
  },
  summaryBadge: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: colors.bgLight,
    paddingVertical: 12,
    borderRadius: 16,
  },
  summaryBadgeValue: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.accent,
    marginBottom: 4,
  },
  summaryBadgeLabel: {
    fontSize: 12,
    color: colors.textMuted,
  },
  todoCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.bgLight,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  todoCardDone: {
    backgroundColor: colors.cardBg,
    borderColor: 'transparent',
    opacity: 0.6,
  },
  todoCheck: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  todoCheckDone: {
    backgroundColor: colors.primary,
  },
  todoCheckText: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.primary,
  },
  todoTextWrap: {
    flex: 1,
  },
  todoText: {
    fontSize: 15,
    color: colors.textDark,
    fontWeight: '500',
    marginBottom: 4,
  },
  todoTextDone: {
    textDecorationLine: 'line-through',
    color: colors.textMuted,
  },
  todoMeta: {
    fontSize: 11,
    color: colors.textMuted,
  },
  emptyCard: {
    padding: 32,
    alignItems: 'center',
    backgroundColor: colors.bgLight,
    borderRadius: 16,
    borderStyle: 'dashed',
    borderWidth: 1,
    borderColor: '#D4CDC4',
  },
  emptyTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textMuted,
    marginBottom: 8,
  },
  emptyBody: {
    fontSize: 13,
    color: '#A39C93',
    textAlign: 'center',
    lineHeight: 18,
  },
  messageCard: {
    padding: 16,
    borderRadius: 20,
    maxWidth: '85%',
  },
  messageCardLeft: {
    backgroundColor: colors.bgLight,
    alignSelf: 'flex-start',
    borderBottomLeftRadius: 4,
  },
  messageCardRight: {
    backgroundColor: colors.primaryLight,
    alignSelf: 'flex-end',
    borderBottomRightRadius: 4,
  },
  messageMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
    gap: 8,
  },
  messageAuthor: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.primary,
  },
  messageTime: {
    fontSize: 11,
    color: colors.textMuted,
  },
  messageContent: {
    fontSize: 15,
    color: colors.textDark,
    lineHeight: 22,
  },
  menuCard: {
    backgroundColor: colors.bgLight,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  menuCardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  menuTitleWrap: {
    flex: 1,
  },
  menuTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textDark,
    marginBottom: 4,
  },
  menuCategory: {
    fontSize: 12,
    color: colors.textMuted,
  },
  orderCountBadge: {
    backgroundColor: colors.accentLight,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  orderCountText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.accent,
  },
  menuDescription: {
    fontSize: 14,
    color: colors.textDark,
    lineHeight: 20,
    marginBottom: 12,
  },
  tagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  tag: {
    backgroundColor: '#EBE5DF',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  tagText: {
    fontSize: 11,
    color: colors.textMuted,
  },
  orderCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.bgLight,
    padding: 16,
    borderRadius: 16,
  },
  orderTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.textDark,
    marginBottom: 4,
  },
  orderMeta: {
    fontSize: 12,
    color: colors.textMuted,
  },
  orderCategory: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.primary,
    backgroundColor: colors.primaryLight,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  wheelEmpty: {
    width: 240,
    height: 240,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.bgLight,
    borderRadius: 120,
    borderWidth: 2,
    borderColor: colors.border,
    borderStyle: 'dashed',
    marginBottom: 24,
  },
  wheelWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 24,
    position: 'relative',
  },
  wheelAnimated: {
    width: 240,
    height: 240,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pointer: {
    position: 'absolute',
    top: -15,
    zIndex: 10,
    width: 0,
    height: 0,
    borderLeftWidth: 15,
    borderRightWidth: 15,
    borderTopWidth: 25,
    borderStyle: 'solid',
    backgroundColor: 'transparent',
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: colors.accent,
  },
  resultCard: {
    marginTop: 20,
    padding: 20,
    backgroundColor: colors.bgLight,
    borderRadius: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  resultLabel: {
    fontSize: 12,
    color: colors.textMuted,
    marginBottom: 8,
  },
  resultValue: {
    fontFamily: headingFont,
    fontSize: 24,
    fontWeight: '800',
    color: colors.primary,
    marginBottom: 8,
  },
  resultHint: {
    fontSize: 13,
    color: colors.textMuted,
    textAlign: 'center',
    lineHeight: 18,
    marginBottom: 16,
  },
});
